version: '3.8'

services:
  # Version GPU NVIDIA
  sentence-transformers:
    build: 
      context: ./embeddings-api
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - MODEL_ID=all-MiniLM-L6-v2
      - USE_CUDA=1
    volumes:
      - embeddings_cache:/app/data
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: 1
              driver: nvidia
    networks:
      - kreacity-ai

volumes:
  embeddings_cache:

networks:
  kreacity-ai:
    external: true
